# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        run: npm i && npm run test
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    env:
    HEROKU_API_KEY: ${secrets.801310e1-eeb5-4d9e-b80a-48b0c905f80c}
    run: heroku container:login
    - name: Build and push
    env:
    HEROKU_API_KEY: ${secrets.801310e1-eeb5-4d9e-b80a-48b0c905f80c}
    run: heroku container:push -a workshop--18 web
    - name: Release
    env:
    HEROKU_API_KEY: ${secrets.801310e1-eeb5-4d9e-b80a-48b0c905f80c}
    run: heroku container:release -a workshop--18 web
   
