# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        run: npm i && npm run test
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 #
        with:
          heroku_api_key: ${{secrets.801310e1-eeb5-4d9e-b80a-48b0c905f80c}}
          heroku_app_name: "workshop--18" #Must be unique in Heroku
          heroku_email: "yulia2232@gmail.com"
